In [56]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
arr = np.array ([1,2,3])
#arr.appened(4) not allowed
arr*2
print(arr)
arr =np.append(arr ,4) #creates anew array
print(arr)
arr.resize(5)
print(arr)
arr.resize(2,3) #2 dimantion array
print(arr)

[1 2 3 4 5]
[1 2 3]
[1 2 3 4]
[1 2 3 4 0]
[[1 2 3]
 [4 0 0]]


In [8]:

arr2 =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)

arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.dtype)
l=[1,2,3,4,5,6,7,8,9]
print(type(l))
arr=np.array([1,2,3,4.999,5,6,7,8,9])
print(arr.dtype)

arr = np.array([22,"nada",888])
print(arr.dtype)




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
int64
<class 'list'>
float64
<U21


In [11]:
zeros =np.zeros((2,3))  #creating an array of zeros
                        #mality demiention in tuple  2 rows 3 colums
print(zeros)

zeros =np.zeros(4) # list
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0.]


In [12]:
ones = np.ones((3,6)) #creating an arry of ones
print(ones)

ones = np.ones(5)
print(ones)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [16]:
range_array = np.arange(10) #creating an array with a specific range
print(range_array)

range_array = np.arange(7,9)  #(start , end )
print(range_array)

range_array = np.arange(7,20,2) # (start ,end , step )
print(range_array)



[0 1 2 3 4 5 6 7 8 9]
[7 8]
[ 7  9 11 13 15 17 19]


In [20]:
# creating an array of evenly spaced value between two numbers
linspace_array = np.linspace(0 ,1, 5)
print(linspace_array)

linspace_array = np.linspace(0 ,100, 8)
print(linspace_array)   #المسفه بين الرقمن تتقسم علي عدد يعني كام خطوه من ال0 الي 100 هنمشي في 8 خطواط

[0.   0.25 0.5  0.75 1.  ]
[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [29]:
#creating an array with random values betwen 0 and 1
random_array = np.random.rand(5)
print(random_array)

random_array = np.random.rand(3,3)
print("r2",random_array)

random_array = np.random.rand(3,3,2)
print("r3",random_array)



random_array = np.random.randint(5)
print(random_array)

random_array = np.random.randint(1,10)
print("r2",random_array)

random_array = np.random.randint(1,10,2)
print("r3",random_array)


random_array = np.random.randint(1,10,(2,2))
print("r3",random_array)

[0.07933705 0.50175359 0.96384052 0.63906322 0.74508307]
r2 [[0.31451186 0.83885026 0.76265656]
 [0.55921972 0.34687934 0.27706918]
 [0.67642215 0.62221914 0.64313538]]
r3 [[[0.19253586 0.17679554]
  [0.59563561 0.3696628 ]
  [0.30490472 0.66637989]]

 [[0.77292176 0.59237884]
  [0.33909286 0.60353846]
  [0.95405987 0.56229908]]

 [[0.90612414 0.65544108]
  [0.37621404 0.92449624]
  [0.42986269 0.44120548]]]
1
r2 4
r3 [1 5]
r3 [[6 6]
 [4 5]]


In [31]:
 #checking the shape oa an array
arr = np.array([[5,7,9,9],[8,9,0,0]])
print(arr.shape)

(2, 4)


In [32]:
#indexing a 1D array
arr = np.array([10,20,30,40,60])
print(arr[0])
print(arr[-1])

10
60


In [33]:
#slicing a 1D array
print(arr[0:2])
print(arr[1:4])

[10 20]
[20 30 40]


In [34]:
#indexing a 2D array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])


1
6


In [38]:
#slicing a 2d array
print(arr[1:,1:])  # frist star and end of row
print(arr[0:2,0:2]) #second start and end of colums
print(arr[0:2,2:])


[[5 6]
 [8 9]]
[[1 2]
 [4 5]]
[[3]
 [6]]


In [41]:
#element-wise addition
arr1 =np.array([1,2,3,4])
arr2 = np.array ([4,5,6,7])
print(arr1+arr2)


#arr1 =np.array([1,2,3,4])
#arr2 = np.array ([4,5,6,])
#print(arr1+arr2)  error because two array must have same size

[ 5  7  9 11]


In [44]:
#array broadcasting
arr = np.array([1,2,3,4,5])
print(arr+10)

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr+10)

[11 12 13 14 15]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [47]:
#matrix multipliction
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(np.dot(arr1,arr2))

arr1 = np.array([[1,2],[3,4],[99,99]]) # بيستخدم الي ينسبه فقط بدون اليرورر
arr2 = np.array([[5,6],[7,8]])
print(np.dot(arr1,arr2))


[[19 22]
 [43 50]]
[[  19   22]
 [  43   50]
 [1188 1386]]


In [51]:
#calculating mean and sum
arr =np.array([1,2,3,4,5,6])
print(np.mean(arr))
print(np.sum(arr))
#Finding Maximum and Minimum Values
print(np.max(arr))
print(np.min(arr))


arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.mean(arr))
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))

3.5
21
6
1
5.0
45
9
1


In [52]:
#practical application
#square matrix
square_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("saquare matrix \n",square_matrix)

saquare matrix 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
#diagonal matrix
diagonal_matrix = np.diag([1,2,3])
print("diagonal matrix \n",diagonal_matrix)

diagonal_matrix = np.diag([1,2,3,9,9])
print("diagonal matrix \n",diagonal_matrix)


diagonal matrix 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
diagonal matrix 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 9 0]
 [0 0 0 0 9]]


In [59]:
#identity matrix
identity_matrix = np.eye(3)
print("identity matrix \n",identity_matrix)

identity matrix 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
#upper triaanger matrix
upper_triangular =np.array([[1,2,3],[0,5,6],[0,0,9]])
print("upper triangular matrix \n",upper_triangular)

upper triangular matrix 
 [[1 2 3]
 [0 5 6]
 [0 0 9]]


In [61]:
#lower triangle matrix
lower_triangle =np.array([[1,0,0],[4,5,0],[7,8,9]])
print(";Lower triangle matrix")
print(lower_triangle)

;Lower triangle matrix
[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [62]:
#symmetric matrix change row to colume
materix =np.array([[1,2,3],[4,5,6]])
print(materix)
transpose_materix = np.transpose(materix)
print(transpose_materix)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [63]:
#trace of a matrix sum the values of diagonal
materix =np.array([[1,2,3],[4,5,6],[7,8,9]])
trace =np.trace(materix)
print(trace)


15


In [64]:
#determinant of a matrix  must square matrix
materix =np.array([[2,3],[5,6]])
determinant = np.linalg.det(materix)
print(determinant)


-2.9999999999999982


In [67]:
#inverse of matrix frist go to linear algeabra

materix =np.array([[2,3],[5,6]])
inverse = np.linalg.inv(materix)
print(materix)
print(inverse)

[[2 3]
 [5 6]]
[[-2.          1.        ]
 [ 1.66666667 -0.66666667]]


In [69]:
#rank of a matrix  ,, row and colum related to each other
#fully range number increasing
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
rank = np.linalg.matrix_rank(matrix)
print(rank)

2
